networks:
  epaper-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  default:
    driver: bridge

services:
  epaper-control:
    build:
      context: ./epaper-control
    ports:
      - "70:70"
    restart: unless-stopped
    volumes:
      - ./epaper-control/untis:/root/untis
      - ./epaper-control/mqtt:/root/mqtt
    networks:
      epaper-net:
        ipv4_address: 172.20.0.2

  epaper-untis:
    build:
      context: ./epaper-untis
    env_file:
      - ./epaper-untis/env.env
    ports:
      - "71:71"
    restart: unless-stopped
    networks:
      epaper-net:
        ipv4_address: 172.20.0.3

  epaper-imagegen:
    build:
      context: ./epaper-imagegen
    volumes:
      - ./epaper-imagegen:/app
    ports:
      - "72:72"
    restart: unless-stopped
    networks:
      epaper-net:
        ipv4_address: 172.20.0.4
  
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1883:1883"  # ← auf allen Interfaces erreichbar
      - "0.0.0.0:9001:9001"
    volumes:
      - ./epaper-control/mosquitto/config:/mosquitto/config
      - ./epaper-control/mosquitto/data:/mosquitto/data
      - ./epaper-control/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      epaper-net:
        ipv4_address: 172.20.0.5
